/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Hospital;

/**
 *
 * @author hp
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    
    Hospital hospital;
    
    public DoctorJPanel(Hospital hospital) {
        initComponents();
        this.hospital = hospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoc = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        lblDocLic = new javax.swing.JLabel();
        lblSpecial = new javax.swing.JLabel();
        lblDocDeg = new javax.swing.JLabel();
        lblDocNum = new javax.swing.JLabel();
        lblDocAdd = new javax.swing.JLabel();
        lblDocTime = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        txtDocLic = new javax.swing.JTextField();
        txtDocSpec = new javax.swing.JTextField();
        txtDocDeg = new javax.swing.JTextField();
        txtDocNum = new javax.swing.JTextField();
        txtDocAdd = new javax.swing.JTextField();
        txtDocTime = new javax.swing.JTextField();
        btnSave6 = new javax.swing.JButton();

        lblDoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoc.setText("Doctor's Information");

        lblDocName.setText("Name:");

        lblDocLic.setText("Licence no:");

        lblSpecial.setText("Speciality:");

        lblDocDeg.setText("Degree:");

        lblDocNum.setText("Contact no:");

        lblDocAdd.setText("Office Address:");

        lblDocTime.setText("Office hours:");

        txtDocSpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocSpecActionPerformed(evt);
            }
        });

        btnSave6.setText("Save");
        btnSave6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocLic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSpecial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocDeg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDocLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave6)
                .addGap(120, 120, 120))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDocAdd, txtDocDeg, txtDocLic, txtDocName, txtDocNum, txtDocSpec, txtDocTime});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblDoc)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocName)
                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocLic)
                    .addComponent(txtDocLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecial)
                    .addComponent(txtDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocDeg)
                    .addComponent(txtDocDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocNum)
                    .addComponent(txtDocNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocAdd)
                    .addComponent(txtDocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocTime)
                    .addComponent(txtDocTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnSave6)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocSpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocSpecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocSpecActionPerformed

    private void btnSave6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave6ActionPerformed
        // TODO add your handling code here:
        
        hospital.setDocname(txtDocName.getText());
        hospital.setDoclicnum(txtDocLic.getText());
        hospital.setSpeciality(txtDocSpec.getText());
        hospital.setDegree(txtDocDeg.getText());
        hospital.setDoccontnum(txtDocNum.getText());
        hospital.setOfficeadd(txtDocAdd.getText());
        hospital.setOfficetime(txtDocTime.getText());
        
        
        JOptionPane.showMessageDialog(this, "Doctor Information Saved");
        
    }//GEN-LAST:event_btnSave6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave6;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblDocAdd;
    private javax.swing.JLabel lblDocDeg;
    private javax.swing.JLabel lblDocLic;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblDocNum;
    private javax.swing.JLabel lblDocTime;
    private javax.swing.JLabel lblSpecial;
    private javax.swing.JTextField txtDocAdd;
    private javax.swing.JTextField txtDocDeg;
    private javax.swing.JTextField txtDocLic;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDocNum;
    private javax.swing.JTextField txtDocSpec;
    private javax.swing.JTextField txtDocTime;
    // End of variables declaration//GEN-END:variables
}
