/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Hospital;

/**
 *
 * @author hp
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceJPanel
     */
    Hospital hospital;
    
    public InsuranceJPanel(Hospital hospital) {
        initComponents();
        this.hospital = hospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInsurance = new javax.swing.JLabel();
        lblCorpID = new javax.swing.JLabel();
        lblInsurAdd = new javax.swing.JLabel();
        lblInsurPrem = new javax.swing.JLabel();
        lblDectAmt = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        txtCorpID = new javax.swing.JTextField();
        txtInsurAdd = new javax.swing.JTextField();
        txtPrem = new javax.swing.JTextField();
        txtDectAmt = new javax.swing.JTextField();
        txtBenefits = new javax.swing.JTextField();
        btnSave7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        lblInsurance.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblInsurance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInsurance.setText("Insurance Details");

        lblCorpID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorpID.setForeground(new java.awt.Color(255, 255, 255));
        lblCorpID.setText("Corporate ID:");

        lblInsurAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInsurAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblInsurAdd.setText("Address:");

        lblInsurPrem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInsurPrem.setForeground(new java.awt.Color(255, 255, 255));
        lblInsurPrem.setText("Premium:");

        lblDectAmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDectAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblDectAmt.setText("Deductable amount:");

        lblBenefits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBenefits.setForeground(new java.awt.Color(255, 255, 255));
        lblBenefits.setText("Benefits:");

        txtPrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPremActionPerformed(evt);
            }
        });

        btnSave7.setBackground(new java.awt.Color(0, 0, 153));
        btnSave7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave7.setForeground(new java.awt.Color(255, 255, 255));
        btnSave7.setText("Save");
        btnSave7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInsurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorpID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInsurAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInsurPrem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDectAmt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBenefits, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInsurAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDectAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorpID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBenefits, txtCorpID, txtDectAmt, txtInsurAdd, txtPrem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorpID)
                    .addComponent(txtCorpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurAdd)
                    .addComponent(txtInsurAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurPrem)
                    .addComponent(txtPrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDectAmt)
                    .addComponent(txtDectAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBenefits)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnSave7)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPremActionPerformed

    private void btnSave7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave7ActionPerformed
        // TODO add your handling code here:
        
        hospital.setCorpid(txtCorpID.getText());
        hospital.setInsuradd(txtInsurAdd.getText());
        hospital.setPremium(txtPrem.getText());
        hospital.setDedctamt(txtDectAmt.getText());
        hospital.setBenefits(txtBenefits.getText());
        
        JOptionPane.showMessageDialog(this, "Insurance Information Saved");
        
        
        
    }//GEN-LAST:event_btnSave7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave7;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorpID;
    private javax.swing.JLabel lblDectAmt;
    private javax.swing.JLabel lblInsurAdd;
    private javax.swing.JLabel lblInsurPrem;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtCorpID;
    private javax.swing.JTextField txtDectAmt;
    private javax.swing.JTextField txtInsurAdd;
    private javax.swing.JTextField txtPrem;
    // End of variables declaration//GEN-END:variables
}
