/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Hospital;

/**
 *
 * @author hp
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    
    Hospital hospital;
    
    public ReportJPanel(Hospital hospital) {
        initComponents();
        
        this.hospital = hospital;
        displayHospital();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReport = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        lblPerson = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        lblContactNum = new javax.swing.JLabel();
        txtBldgrp = new javax.swing.JTextField();
        lblBldgrp = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtWeb = new javax.swing.JTextField();
        txtCountry1 = new javax.swing.JTextField();
        lblAdd = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCountry1 = new javax.swing.JLabel();
        txtGPS = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblDriver = new javax.swing.JLabel();
        lblLicNum = new javax.swing.JLabel();
        lblIssue = new javax.swing.JLabel();
        lblValid = new javax.swing.JLabel();
        txtLicNum = new javax.swing.JTextField();
        txtIssue = new javax.swing.JTextField();
        txtValid = new javax.swing.JTextField();
        lblVehicle = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblNumPlate = new javax.swing.JLabel();
        lblChassis = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtNumPlate = new javax.swing.JTextField();
        txtChassis = new javax.swing.JTextField();
        lblPatient = new javax.swing.JLabel();
        lblPatID = new javax.swing.JLabel();
        LBLPrimDoc = new javax.swing.JLabel();
        lblLastVis = new javax.swing.JLabel();
        lblAllergy = new javax.swing.JLabel();
        txtNextVis = new javax.swing.JTextField();
        lblMed = new javax.swing.JLabel();
        lblNextVis = new javax.swing.JLabel();
        txtPatID = new javax.swing.JTextField();
        txtPrimDoc = new javax.swing.JTextField();
        txtLastVis = new javax.swing.JTextField();
        lblDocAdd = new javax.swing.JLabel();
        lblDocTime = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        txtDocLic = new javax.swing.JTextField();
        txtDocSpec = new javax.swing.JTextField();
        lblDoc = new javax.swing.JLabel();
        txtDocDeg = new javax.swing.JTextField();
        lblDocName = new javax.swing.JLabel();
        txtDocNum = new javax.swing.JTextField();
        lblDocLic = new javax.swing.JLabel();
        txtDocAdd = new javax.swing.JTextField();
        lblSpecial = new javax.swing.JLabel();
        txtDocTime = new javax.swing.JTextField();
        lblDocDeg = new javax.swing.JLabel();
        lblDocNum = new javax.swing.JLabel();
        txtBenefits = new javax.swing.JTextField();
        lblInsurance = new javax.swing.JLabel();
        lblCorpID = new javax.swing.JLabel();
        lblInsurAdd = new javax.swing.JLabel();
        lblInsurPrem = new javax.swing.JLabel();
        lblDectAmt = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        txtCorpID = new javax.swing.JTextField();
        txtInsurAdd = new javax.swing.JTextField();
        txtPrem = new javax.swing.JTextField();
        txtDectAmt = new javax.swing.JTextField();
        txtAllergy = new javax.swing.JTextField();
        txtMed = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        lblReport.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("Patient Report");

        lblWeb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWeb.setForeground(new java.awt.Color(255, 255, 255));
        lblWeb.setText("Website:");

        lblMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMail.setForeground(new java.awt.Color(255, 255, 255));
        lblMail.setText("Email id:");

        lblPerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerson.setText("Person Information");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");

        lblDOB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblDOB.setText("Date of Birth:");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender:");

        lblCountry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(255, 255, 255));
        lblCountry.setText("Country:");
        lblCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblContactNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContactNum.setForeground(new java.awt.Color(255, 255, 255));
        lblContactNum.setText("Contact no:");

        txtBldgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBldgrpActionPerformed(evt);
            }
        });

        lblBldgrp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBldgrp.setForeground(new java.awt.Color(255, 255, 255));
        lblBldgrp.setText("Blood group:");

        lblSSN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(255, 255, 255));
        lblSSN.setText("SSN no:");

        txtCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountry1ActionPerformed(evt);
            }
        });

        lblAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdd.setText("Address Details");

        lblGPS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGPS.setForeground(new java.awt.Color(255, 255, 255));
        lblGPS.setText("GPS Location:");

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setText("State:");

        lblCountry1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCountry1.setForeground(new java.awt.Color(255, 255, 255));
        lblCountry1.setText("Country:");

        lblDriver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriver.setText("Driver's Information");

        lblLicNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLicNum.setForeground(new java.awt.Color(255, 255, 255));
        lblLicNum.setText("Licence Number:");

        lblIssue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIssue.setForeground(new java.awt.Color(255, 255, 255));
        lblIssue.setText("Issue date:");

        lblValid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValid.setForeground(new java.awt.Color(255, 255, 255));
        lblValid.setText("Valid through:");

        lblVehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicle.setText("Vehicle Registration Details");

        lblModel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");

        lblSerial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSerial.setForeground(new java.awt.Color(255, 255, 255));
        lblSerial.setText("Serial no:");

        lblNumPlate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumPlate.setForeground(new java.awt.Color(255, 255, 255));
        lblNumPlate.setText("Number plate:");

        lblChassis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChassis.setForeground(new java.awt.Color(255, 255, 255));
        lblChassis.setText("Chassis no:");

        txtSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialActionPerformed(evt);
            }
        });

        txtChassis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassisActionPerformed(evt);
            }
        });

        lblPatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatient.setText("Patient Information");

        lblPatID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPatID.setForeground(new java.awt.Color(255, 255, 255));
        lblPatID.setText("Patient ID:");

        LBLPrimDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBLPrimDoc.setForeground(new java.awt.Color(255, 255, 255));
        LBLPrimDoc.setText("Primary doctor:");

        lblLastVis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastVis.setForeground(new java.awt.Color(255, 255, 255));
        lblLastVis.setText("Last visit date:");

        lblAllergy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAllergy.setForeground(new java.awt.Color(255, 255, 255));
        lblAllergy.setText("Any allergies:");

        lblMed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMed.setForeground(new java.awt.Color(255, 255, 255));
        lblMed.setText("On Medication:");

        lblNextVis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNextVis.setForeground(new java.awt.Color(255, 255, 255));
        lblNextVis.setText("Date of next visit:");

        lblDocAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblDocAdd.setText("Office Address:");

        lblDocTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDocTime.setText("Office hours:");

        txtDocSpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocSpecActionPerformed(evt);
            }
        });

        lblDoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoc.setText("Doctor's Information");

        lblDocName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocName.setForeground(new java.awt.Color(255, 255, 255));
        lblDocName.setText("Name:");

        lblDocLic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocLic.setForeground(new java.awt.Color(255, 255, 255));
        lblDocLic.setText("Licence no:");

        lblSpecial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpecial.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecial.setText("Speciality:");

        lblDocDeg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocDeg.setForeground(new java.awt.Color(255, 255, 255));
        lblDocDeg.setText("Degree:");

        lblDocNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocNum.setForeground(new java.awt.Color(255, 255, 255));
        lblDocNum.setText("Contact no:");

        lblInsurance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInsurance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInsurance.setText("Insurance Details");

        lblCorpID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorpID.setForeground(new java.awt.Color(255, 255, 255));
        lblCorpID.setText("Corporate ID:");

        lblInsurAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInsurAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblInsurAdd.setText("Address:");

        lblInsurPrem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInsurPrem.setForeground(new java.awt.Color(255, 255, 255));
        lblInsurPrem.setText("Premium:");

        lblDectAmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDectAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblDectAmt.setText("Deductable amount:");

        lblBenefits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBenefits.setForeground(new java.awt.Color(255, 255, 255));
        lblBenefits.setText("Benefits:");

        txtPrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPremActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblContactNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblBldgrp, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblWeb, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBldgrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(lblMail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(lblCountry)
                            .addGap(12, 12, 12)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumPlate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblChassis, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBLPrimDoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLastVis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAllergy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMed, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNextVis, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrimDoc)
                            .addComponent(txtLastVis)
                            .addComponent(txtNextVis)
                            .addComponent(txtPatID, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtAllergy)
                            .addComponent(txtMed, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDocName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDocLic, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSpecial, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDocDeg, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDocNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDocAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDocTime, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDocLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorpID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInsurAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInsurPrem, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDectAmt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBenefits, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInsurAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDectAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorpID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGPS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblState, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCountry1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGPS, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtCity)))
                            .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLicNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIssue, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValid, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIssue, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLicNum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValid, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCity, txtCountry1, txtGPS, txtState});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLastVis, txtNextVis, txtPatID, txtPrimDoc});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtChassis, txtModel, txtNumPlate, txtSerial});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDocAdd, txtDocDeg, txtDocLic, txtDocName, txtDocNum, txtDocSpec, txtDocTime});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBenefits, txtCorpID, txtDectAmt, txtInsurAdd, txtPrem});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtBldgrp, txtCountry, txtDOB, txtGender, txtMail, txtName, txtNum, txtSSN, txtWeb});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblReport)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblPerson)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(lblContactNum)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(lblBldgrp)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBldgrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDOB)
                                    .addComponent(lblSSN)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(lblWeb)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblDriver))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicNum)
                                    .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIssue)
                                    .addComponent(txtIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValid)
                                    .addComponent(txtValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGPS)
                                    .addComponent(txtGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCity)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblState)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCountry1)
                                    .addComponent(txtCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCountry)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMail)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatient, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInsurance, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCorpID)
                                    .addComponent(txtCorpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblInsurAdd)
                                    .addComponent(txtInsurAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblInsurPrem)
                                    .addComponent(txtPrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDectAmt)
                                    .addComponent(txtDectAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBenefits)
                                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblPatID)
                                            .addComponent(txtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBLPrimDoc)
                                            .addComponent(txtPrimDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLastVis)
                                            .addComponent(txtLastVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAllergy)
                                            .addComponent(txtAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblMed)
                                            .addComponent(txtMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVehicle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblModel)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSerial)
                                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblNumPlate)
                                            .addComponent(txtNumPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblChassis)
                                            .addComponent(txtChassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNextVis)
                                    .addComponent(txtNextVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocName)
                            .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocLic)
                            .addComponent(txtDocLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpecial)
                            .addComponent(txtDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocDeg)
                            .addComponent(txtDocDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocNum)
                            .addComponent(txtDocNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocAdd)
                            .addComponent(txtDocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocTime)
                            .addComponent(txtDocTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBldgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBldgrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBldgrpActionPerformed

    private void txtCountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountry1ActionPerformed

    private void txtSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialActionPerformed

    private void txtChassisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassisActionPerformed

    private void txtDocSpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocSpecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocSpecActionPerformed

    private void txtPremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPremActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLPrimDoc;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergy;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblBldgrp;
    private javax.swing.JLabel lblChassis;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNum;
    private javax.swing.JLabel lblCorpID;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCountry1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDectAmt;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblDocAdd;
    private javax.swing.JLabel lblDocDeg;
    private javax.swing.JLabel lblDocLic;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblDocNum;
    private javax.swing.JLabel lblDocTime;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInsurAdd;
    private javax.swing.JLabel lblInsurPrem;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblIssue;
    private javax.swing.JLabel lblLastVis;
    private javax.swing.JLabel lblLicNum;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMed;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNextVis;
    private javax.swing.JLabel lblNumPlate;
    private javax.swing.JLabel lblPatID;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSpecial;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblValid;
    private javax.swing.JLabel lblVehicle;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtBldgrp;
    private javax.swing.JTextField txtChassis;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCorpID;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtCountry1;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDectAmt;
    private javax.swing.JTextField txtDocAdd;
    private javax.swing.JTextField txtDocDeg;
    private javax.swing.JTextField txtDocLic;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDocNum;
    private javax.swing.JTextField txtDocSpec;
    private javax.swing.JTextField txtDocTime;
    private javax.swing.JTextField txtGPS;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtInsurAdd;
    private javax.swing.JTextField txtIssue;
    private javax.swing.JTextField txtLastVis;
    private javax.swing.JTextField txtLicNum;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMed;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNextVis;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtNumPlate;
    private javax.swing.JTextField txtPatID;
    private javax.swing.JTextField txtPrem;
    private javax.swing.JTextField txtPrimDoc;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtValid;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables

    private void displayHospital() {
        
        txtName.setText(hospital.getName());
        System.out.println("personName:"+hospital.getName());
        txtAge.setText(hospital.getAge());
        System.out.println("personAge:"+hospital.getAge());
        txtDOB.setText(hospital.getDob());
        System.out.println("personDateOfBirth:"+hospital.getDob());
        txtGender.setText(hospital.getGender());
        System.out.println("personGender:"+hospital.getGender());
        txtCountry.setText(hospital.getCountry());
        System.out.println("personCountry:"+hospital.getCountry());
        txtNum.setText(hospital.getMobnum());
        System.out.println("personMobileNumber:"+hospital.getMobnum());
        txtBldgrp.setText(hospital.getBldgrp());
        System.out.println("personBloodGroup:"+hospital.getBldgrp());
        txtSSN.setText(hospital.getSsnnum());
        System.out.println("personSSNnumber:"+hospital.getSsnnum());
        txtWeb.setText(hospital.getWeb());
        System.out.println("personWebsite:"+hospital.getWeb());
        txtMail.setText(hospital.getEmail());
        System.out.println("personEmail:"+hospital.getEmail());
        txtGPS.setText(hospital.getGpsloc());
        System.out.println("GPSLocation:"+hospital.getGpsloc());
        txtCity.setText(hospital.getCity());
        System.out.println("CityName:"+hospital.getCity());
        txtState.setText(hospital.getState());
        System.out.println("StateName:"+hospital.getState());
        txtCountry1.setText(hospital.getCountry2());
        System.out.println("CountryName:"+hospital.getCountry2());
        txtLicNum.setText(hospital.getCarlicnum());
        System.out.println("CarLicenceNumber:"+hospital.getCarlicnum());
        txtIssue.setText(hospital.getIssuedate());
        System.out.println("IssueDate:"+hospital.getIssuedate());
        txtValid.setText(hospital.getValiddate());
        System.out.println("ValidThroughDate:"+hospital.getValiddate());
        txtModel.setText(hospital.getModel());
        System.out.println("ModelName:"+hospital.getModel());
        txtSerial.setText(hospital.getSerialnum());
        System.out.println("SerialNumber:"+hospital.getSerialnum());
        txtNumPlate.setText(hospital.getNumplate());
        System.out.println("Number Plate:"+hospital.getNumplate());
        txtChassis.setText(hospital.getChassisnum());
        System.out.println("Chassis Number:"+hospital.getChassisnum());
        txtPatID.setText(hospital.getPatid());
        System.out.println("Parient ID:"+hospital.getPatid());
        txtPrimDoc.setText(hospital.getPrimdoc());
        System.out.println("Primary Doctor:"+hospital.getPrimdoc());
        txtLastVis.setText(hospital.getLastvisit());
        System.out.println("Date of last visit:"+hospital.getLastvisit());
        txtNextVis.setText(hospital.getNextvisit());
        System.out.println("Date of next visit:"+hospital.getNextvisit());
        txtAllergy.setText(hospital.getAllergy());
        System.out.println("Any allergies:"+hospital.getAllergy());
        txtMed.setText(hospital.getMed());
        System.out.println("On any medication:"+hospital.getMed());
        txtDocName.setText(hospital.getDocname());
        System.out.println("Doctor name:"+hospital.getDocname());
        txtDocLic.setText(hospital.getDoclicnum());
        System.out.println("Doctor licence number:"+hospital.getDoclicnum());
        txtDocSpec.setText(hospital.getSpeciality());
        System.out.println("Speciality:"+hospital.getSpeciality());
        txtDocDeg.setText(hospital.getDegree());
        System.out.println("Degree holding:"+hospital.getDegree());
        txtDocNum.setText(hospital.getDoccontnum());
        System.out.println("Doctors contact number:"+hospital.getDoccontnum());
        txtDocAdd.setText(hospital.getOfficeadd());
        System.out.println("Hospital address:"+hospital.getOfficeadd());
        txtDocTime.setText(hospital.getOfficetime());
        System.out.println("Hospital time:"+hospital.getOfficetime());
        txtCorpID.setText(hospital.getCorpid());
        System.out.println("Corporate ID:"+hospital.getCorpid());
        txtInsurAdd.setText(hospital.getInsuradd());
        System.out.println("Insurance address:"+hospital.getInsuradd());
        txtPrem.setText(hospital.getPremium());
        System.out.println("Premium:"+hospital.getPremium());
        txtDectAmt.setText(hospital.getDedctamt());
        System.out.println("Deductable amount:"+hospital.getDedctamt());
        txtBenefits.setText(hospital.getBenefits());
        System.out.println("Benefits:"+hospital.getBenefits());
       
        
        
    }
}
